language: python
python:
     - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

env:
    - PLATFORMIO_CI_SRC="examples/160 x 128/Arduino_Life"
    - PLATFORMIO_CI_SRC="examples/Sprite/Transparent_Sprite_Demo"
    
script:
    - platformio ci --lib="." --board=nodemcuv2 --project-conf=Continous_Integration/travis.ini
