language: python
python:
     - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

env:
    - PLATFORMIO_CI_SRC="examples/160 x 128/Arduino_Life"

script:
    - platformio ci --lib="." --board=nodemcuv2  --project-conf=platformio.ini
